### ISSUE TITLE
Please push 1.0 release to maven central.

### ISSUE THREAD

**Issue by maxdemarzi** [FastFilter/fastfilter_java#25]
Thank you!

**Comment by lemire** [comment]
This seems reasonable.

@thomasmueller Can you do it? If not, I can set something up.

**Comment by thomasmueller** [comment]
Sure, I will try

Daniel Lemire ***@***.***> schrieb am Mo., 26. Apr. 2021,
15:05:

**Comment by thomasmueller** [comment]
We currently have 

<groupId>org.fastfilter</groupId>
<artifactId>fastfilter_java</artifactId>

I think Maven Central (Sonatype) will require that we either
* A: register fastfilter.org (which seems not reasonable currently), or 
* B: (probably simpler) change the group id, I think to "com.github.fastFilter".

I will try approach B. OK?

**Comment by richardstartin** [comment]
B makes sense to me

**Comment by lemire** [comment]
I think that 99% of programmers out there are not impressed by custom domains and will happily take com.github.fastFilter or something like that. Whether the software is well tested and documented matters more.

**Comment by thomasmueller** [comment]
OK I changed groupId and artifactId... now the question is: should we also change the package names from org.fastfilter to com.github.fastfilter. I think it's not needed.

**Comment by lemire** [comment]
Someone could buy fastfilter.org and then sue you for trademark violation. 

I kid.

I think it is fine to keep the package names unchanged. Though if you are going to change them one day, you might as well do it now.

**Comment by richardstartin** [comment]
I recommend doing it now. I can't think of concrete examples off the top of my head, but as a user I have always found it annoying when the group id is not a prefix of the packages.

**Comment by thomasmueller** [comment]
OK, changed it.

**Comment by thomasmueller** [comment]
Some more work is needed, I'm following the documentation at https://central.sonatype.org/publish/publish-maven/
It will probably take a few more days until everything is set up properly.

**Comment by thomasmueller** [comment]
Created https://issues.sonatype.org/browse/OSSRH-68199

**Comment by lemire** [comment]
It is a whole lot of fun. 

See https://github.com/RoaringBitmap/RoaringBitmap/issues/454

On the plus side, it seems to be getting a whole lot better.

**Comment by thomasmueller** [comment]
According to https://issues.sonatype.org/browse/OSSRH-68199 we can't use the groupId com.github.fastfilter, and need to use io.github.fastfilter. I created an initial Github page: https://fastfilter.github.io/

Which package name should we use?
* com.github.fastfilter
* io.github.fastfilter
* org.fastfilter

I vote for org.fastfilter. io.github.fastfilter is weird in my view. The disavantage of both github options is, if we switch hosting to e.g. GitLab we would have to change the package name. I know we would also have to change the groupId, but groupId is typically only use in one place (pom.xml), so that's less of a concern.

**Comment by lemire** [comment]
We could acquire fastfilter.org and use that throughout and be done with the issue.

https://www.namecheap.com/domains/registration/results/?domain=fastfilter.org

I can get it if you'd like and put some landing page on it.

**Comment by thomasmueller** [comment]
I'm OK to use io.github.fastfilter as the groupId. Just the Java package name, I think org.fastfilter is better. Registering the domain would allow us to use org.fastfilter as the Maven groupId. I'm not sure if that's worth it... It is a bit a hassle I have to admit. I think the risk is low that someone would register fastfilter.org such that we would have to change the package name.

**Comment by lemire** [comment]
I agree that using org.fastfilter is probably quite fine.

**Comment by thomasmueller** [comment]
Snapshot build is here: https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/fastfilter/fastfilter/1.0-SNAPSHOT/

**Comment by thomasmueller** [comment]
For future reference, to deploy:

    # change version number
    cd fastfilter
    mvn -Prelease-sign-artifacts clean deploy

**Comment by thomasmueller** [comment]
Release 1.0 is here: https://s01.oss.sonatype.org/content/repositories/releases/io/github/fastfilter/fastfilter/1.0/fastfilter-1.0.pom

**Comment by thomasmueller** [comment]
It might take some time until Sonatype activated sync for this library (it sounds like this is a manual step on their side). Please re-open if this doesn't work for some time.

**Comment by thomasmueller** [comment]
Oh, already synched: https://repo1.maven.org/maven2/io/github/fastfilter/fastfilter/1.0/fastfilter-1.0.pom
